# chronik/genesis_trigger.yaml
# Dies ist der Auslöser für den Genesis-Ritualstart (Kommentar auf Deutsch)

meta:
  id: genesis_trigger
  version: 1.0
  created: 2025-12-07T21:53:00Z
  author: CoreCraftSystems

trigger:
  name: "Genesis Ritual Start"
  description: "Initialization of a new audit-sealed act"
  type: manual

conditions:
  - check: "environment_ready"
    description: "All modules loaded, no open errors"
  - check: "audit_log_append_only"
    description: "Audit log is active and immutable"

actions:
  - step: "create_anchor"
    file: "chronik/genesis_anchor.yaml"
    description: "Symbolic anchoring of the genesis act"
  - step: "notify"
    channel: "dashboard"
    message: "Genesis ritual triggered"
